import { expect, it } from 'vitest';
import { PDFDocument, PDFDict, PDFArray, PDFName, PDFRawStream, decodePDFRawStream } from 'pdf-lib';
import { analyzeProject } from '../../../engine/solver';
import { summarizeNtcSteelTensionDesign } from '../../../design/ntcSteel2023';
import { steelTensionProject } from '../../../design/fixtures/steelTensionProject';
import { buildSteelReviewPdf } from './steelReviewPdf';

it('exporta la revisión incompleta con el modelo que reproduce demanda y resistencia', async () => {
  const model = steelTensionProject(true), combination = model.combinations[0]!;
  model.members.push({ ...model.members[0]!, id: 'T2' });
  model.nodalLoads[0]!.fx *= 2; model.nodalLoads[0]!.fy *= 2;
  const summary = summarizeNtcSteelTensionDesign({ project: { ...model, members: model.members.slice(0, 1) }, analysis: analyzeProject(model, combination), combinationId: combination.id });
  const bytes = await buildSteelReviewPdf({ projectName: model.name, model, combination, summary }, new Date('2026-10-04T10:00:00Z'));
  const pdf = await PDFDocument.load(bytes);
  expect(pdf.getTitle()).toContain('revisión parcial');
  expect(pdf.getPageCount()).toBeGreaterThan(0);
  const names = pdf.catalog.lookup(PDFName.of('Names'), PDFDict).lookup(PDFName.of('EmbeddedFiles'), PDFDict).lookup(PDFName.of('Names'), PDFArray);
  const spec = names.lookup(1, PDFDict);
  const stream = spec.lookup(PDFName.of('EF'), PDFDict).lookup(PDFName.of('F')) as PDFRawStream;
  const attached = JSON.parse(new TextDecoder().decode(decodePDFRawStream(stream).decode()));
  expect(attached.model).toEqual(model);
  expect(attached.selection.memberIds).toEqual(['T1']);
  expect(attached.summary.statusConclusion).toBe('incomplete');
  expect(attached.summary.highest.demand.value).toBeCloseTo(100, 7);
  expect(attached.summary.highest.resistance.value).toBeCloseTo(.9 * 345000 * .0017290288, 7);
  expect(attached.summary.highest.missingChecks).toContain('net-section-fracture');
  expect(attached.summary.highest.standard.sourceSha256).toMatch(/^[a-f0-9]{64}$/);
  const replay = summarizeNtcSteelTensionDesign({ project: { ...attached.model, members: attached.model.members.filter((m: { id: string }) => attached.selection.memberIds.includes(m.id)) }, analysis: analyzeProject(attached.model, attached.model.combinations[0]), combinationId: attached.combinationId });
  expect(replay).toEqual(summary);
});
